/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.10
 * Generated at: 2018-08-11 12:44:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("    <title>News Feed</title>\n");
      out.write("</head>\n");
      out.write("<link rel=\"stylesheet\" href=\"home.css\"/>\n");
      out.write("<script type=\"text/javascript\" src=\"jquery-3.3.1.min.js\"></script>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    $(document).ready(function(){\n");
      out.write("        var jsonData = \"\";\n");
      out.write("        $.ajax({\n");
      out.write("            beforeSend: function(){\n");
      out.write("                $(\"#article\").hide();\n");
      out.write("                $(\".loader\").show();\n");
      out.write("            },\n");
      out.write("            url: \"firststruts/fetchJSON\",\n");
      out.write("            success: function(response){\n");
      out.write("                if(response.indexOf(\"ERROR\")){\n");
      out.write("                    jsonData = JSON.parse(response);\n");
      out.write("                    var newsTable = $(\"#article\").find(\"tbody\");\n");
      out.write("                    for(i = 0;i < jsonData.length;i++){\n");
      out.write("                        var str = \"<tr><td><a href='\"+jsonData[i].link+\"'>\"+jsonData[i].article+\"</a></td><td>\"+jsonData[i].publisher+\"</td></tr>\";\n");
      out.write("                        newsTable.append(str);\n");
      out.write("                    }\n");
      out.write("                    $(\"#article\").show();\n");
      out.write("                    $(\".loader\").hide();\n");
      out.write("                }\n");
      out.write("                else{\n");
      out.write("                    $(\".loader\").hide();\n");
      out.write("                    $(\".headerPart\").hide();    \n");
      out.write("                    $(\".errormsg\").html(\"<h1>Sorry....Try Again</h1>\");   \n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $(\"#sort\").click(function(){\n");
      out.write("            if(jsonData != \"\"){\n");
      out.write("                $(\"#article\").hide();\n");
      out.write("                $(\".loader\").show();\n");
      out.write("                jsonData.sort(function(a,b){\n");
      out.write("                    if (a.publisher == b.publisher) return 0;\n");
      out.write("                    if (a.publisher > b.publisher) return 1;\n");
      out.write("                    if (a.publisher < b.publisher) return -1;\n");
      out.write("                });\n");
      out.write("               var newsTable = $(\"#article\").find(\"tbody\");\n");
      out.write("               $(newsTable).empty();\n");
      out.write("               for(i = 0;i < jsonData.length;i++){\n");
      out.write("                    var str = \"<tr><td><a href='\"+jsonData[i].link+\"'>\"+jsonData[i].article+\"</a></td><td>\"+jsonData[i].publisher+\"</td></tr>\";\n");
      out.write("                    newsTable.append(str);\n");
      out.write("                } \n");
      out.write("                $(\"#article\").show();\n");
      out.write("                $(\".loader\").hide();\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $(\"#search\").click(function(){\n");
      out.write("            var searchText = $(\"#searchText\").val();\n");
      out.write("            if(searchText != \"\"){\n");
      out.write("                $(\"#article\").hide();\n");
      out.write("                $(\".loader\").show();\n");
      out.write("                var newsTable = $(\"#article\").find(\"tbody\");\n");
      out.write("                $(newsTable).empty();\n");
      out.write("                for(i = 0;i < jsonData.length;i++){\n");
      out.write("                    if(jsonData[i].article.indexOf(searchText) >= 0){\n");
      out.write("                        var str = \"<tr><td><a href='\"+jsonData[i].link+\"'>\"+jsonData[i].article+\"</a></td><td>\"+jsonData[i].publisher+\"</td></tr>\";\n");
      out.write("                        newsTable.append(str);\n");
      out.write("                    }\n");
      out.write("                } \n");
      out.write("                $(\"#article\").show();\n");
      out.write("                $(\".loader\").hide();\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $(\"#clearSearch\").click(function(){\n");
      out.write("            var searchText = $(\"#searchText\").val();\n");
      out.write("            if(jsonData!=\"\" && searchText!=\"\"){\n");
      out.write("                $(\"#article\").hide();\n");
      out.write("                $(\".loader\").show();\n");
      out.write("                var newsTable = $(\"#article\").find(\"tbody\");\n");
      out.write("                $(newsTable).empty();\n");
      out.write("                for(i = 0;i < jsonData.length;i++){\n");
      out.write("                    var str = \"<tr><td><a href='\"+jsonData[i].link+\"'>\"+jsonData[i].article+\"</a></td><td>\"+jsonData[i].publisher+\"</td></tr>\";\n");
      out.write("                    newsTable.append(str);\n");
      out.write("                }\n");
      out.write("                $(\"#searchText\").val(\"\");\n");
      out.write("                $(\"#article\").show();\n");
      out.write("                $(\".loader\").hide();\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("</script>\n");
      out.write("<body>\n");
      out.write("    <div class=\"loader\"></div>\n");
      out.write("    <div class=\"errormsg\"></div>\n");
      out.write("    <div class=\"headerPart\">\n");
      out.write("        <div class=\"heading\"> News Feed </div> \n");
      out.write("        <div class=\"searchOrSort\">\n");
      out.write("            <input id=\"searchText\" type=\"text\" placeholder=\"Search by Article\" />\n");
      out.write("            <button id=\"search\" class=\"search\">Search</button>\n");
      out.write("            <button id=\"clearSearch\" class=\"clear\">Clear</button>\n");
      out.write("            <button id='sort' class=\"sort\">Sort By Publisher</button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div>\n");
      out.write("        <table id = \"article\">\n");
      out.write("            <thead>\n");
      out.write("                <th>Article</th>\n");
      out.write("                <th>Publisher</th>\n");
      out.write("            </thead>\n");
      out.write("            <tbody>            \n");
      out.write("            </tbody>\n");
      out.write("        </table>\n");
      out.write("    </div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
